// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWzwGzltNDgCnVp3fANwtJo0dtFOdiU5U',
    appId: '1:1053849124691:web:bcd39d877c319a7ab2eba6',
    messagingSenderId: '1053849124691',
    projectId: 'fir-task-bb097',
    authDomain: 'fir-task-bb097.firebaseapp.com',
    storageBucket: 'fir-task-bb097.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOn4i2S6i3jHlQI-wddPLFt1yYv_1qos',
    appId: '1:1053849124691:android:f14b6a852733f578b2eba6',
    messagingSenderId: '1053849124691',
    projectId: 'fir-task-bb097',
    storageBucket: 'fir-task-bb097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy3I6mbB9skEDM34vffHwHr_M6dH0pT9c',
    appId: '1:1053849124691:ios:a40e1a3097a42bd2b2eba6',
    messagingSenderId: '1053849124691',
    projectId: 'fir-task-bb097',
    storageBucket: 'fir-task-bb097.appspot.com',
    iosBundleId: 'com.example.imageGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy3I6mbB9skEDM34vffHwHr_M6dH0pT9c',
    appId: '1:1053849124691:ios:a24f7be2e7f55b9fb2eba6',
    messagingSenderId: '1053849124691',
    projectId: 'fir-task-bb097',
    storageBucket: 'fir-task-bb097.appspot.com',
    iosBundleId: 'com.example.imageGallery.RunnerTests',
  );
}
